# Generated by Django 2.2.1 on 2019-06-11 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dealership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('engine_m3', models.FloatField()),
                ('dealership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealership.Dealership')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealership.Manufacturer')),
            ],
        ),
    ]
